### ISSUE TITLE
Test Answers to Questions

### ISSUE THREAD

**Issue by imsoncod** [tanreinama/text2text-japanese#1]
Thank you for the great code :)

I tested the learning data by changing it to 'QtoA' form of question answering instead of news.
However, the model did not give a proper answer. Have you ever tested anything other than news data?

+ Is there a reason why we have to divide the learning data into txt files and convert them into pkl files?
ex) I think this will be easier.
[data.txt]
Question1<|SEP|>Answer1.
Question2<|SEP|>Answer2.
Question3<|SEP|>Answer3.

Have a nice day.

**Comment by tanreinama** [comment]
Unfortunately, there are not many types of tests available, as there are few types of Japanese corpora available.
Yes, maybe I haven't tested the kind of QA task you want.
Reasons to create a pkl file:
Text encoding is very slow. Therefore, it runs in multiple processes using a lot of CPUs. This is important when encoding sizes larger than a few GB; encoding on an instance with a lot of CPUs (eg AWS c5a, 24xlarge) and training on another type of instance (eg p3.2xlarge) .
thank you.

**Comment by imsoncod** [comment]
I understand, thank you.
I know GPT2 is a model that predicts the next word. Can I see the process tensorflow infers?
ex)
I
I am
I am a
I am a boy

+ The speed of reasoning seems to be slow, 5-10 seconds. I wonder if there is any way to improve it.
For example other frameworks(pytorch, mxnet)

**Comment by tanreinama** [comment]
New tokens are generated one by one with tf.while_loop in sampling.py.
In the body1-2 function, the token is selected from the possibility column. In here, you can change the "samples" so that you can select the token anywhere. (If you want to see only the most likely ones, --top_k = 1 is easy)
It's slow due to the GPT2 mechanism of generating new tokens one by one. Because Transformers are executed as many as the number of tokens to be generated!
Reducing --max_length reduces the number of loops and improves speed.

**Comment by imsoncod** [comment]
Oh~ That's really amazing. Thank you.
The learning process was very fast. Is 'max_train_steps' different from the general 'epoch_num'?
And, I am wondering why permutation of global_chunks and what is the role of global_chunk_index.

I trained with'max_train_steps' set to 10000, but the value of global_chunk_index was fixed during training.
I am wondering if you are learning as much as 'max_train_steps' with all the data at once.
(Is it because batch_size is 1?😶)

**Comment by tanreinama** [comment]
Yeah. Learning is fast. Because there is no loop like when it was generate.
The pkl file stores the data in the order in which they were read, but this order is sometimes biased (clusters can be created for each corpus, such as when using multiple corpora).
However, when learning, we want to learn in a random order, so we use global_chunk_index.
The reason for specifying steps instead of epoch_num is that sometimes the corpus size is larger than 1 epoch. epochs is calculated by steps / (corpus size(num tokens) / 1024).

**Comment by imsoncod** [comment]
Thank you very much.
As the length was shortened, the response speed decreased within 1 second.
I will continue to develop. If there is a bug, I will leave an issue :)
